name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *' # Atualiza diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: jstrieb/github-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          username: "DevBielCastro"

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub stats" || echo "Sem alterações"
          git push
