name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          git clone https://github.com/jstrieb/github-stats.git stats-temp
          cd stats-temp
          npm ci

      - name: Generate Stats Images
        run: |
          cd stats-temp
          ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} node generate_images.js
          # Copia as imagens geradas pro seu repositório
          cp -R generated/* ../generated/

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add generated
          git commit -m "Update GitHub stats" || echo "Nothing to commit"
          git push
